//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vhudson-jaxb-ri-2.1-2 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2023.07.07 at 06:43:39 PM EEST 
//


package com.game_classes.soap_models;

import javax.xml.bind.JAXBElement;
import javax.xml.bind.annotation.XmlElementDecl;
import javax.xml.bind.annotation.XmlRegistry;
import javax.xml.namespace.QName;


/**
 * This object contains factory methods for each 
 * Java content interface and Java element interface 
 * generated in the com.game_classes.soap_models package. 
 * <p>An ObjectFactory allows you to programatically 
 * construct new instances of the Java representation 
 * for XML content. The Java representation of XML 
 * content can consist of schema derived interfaces 
 * and classes representing the binding of schema 
 * type definitions, element declarations and model 
 * groups.  Factory methods for each of these are 
 * provided in this class.
 * 
 */
@XmlRegistry
public class ObjectFactory {

    private final static QName _RankingRequest_QNAME = new QName("http://www.game_classes.com/soap-models", "RankingRequest");

    /**
     * Create a new ObjectFactory that can be used to create new instances of schema derived classes for package: com.game_classes.soap_models
     * 
     */
    public ObjectFactory() {
    }

    /**
     * Create an instance of {@link RankingDataSoapList }
     * 
     */
    public RankingDataSoapList createRankingDataSoapList() {
        return new RankingDataSoapList();
    }

    /**
     * Create an instance of {@link RankingDataSoap }
     * 
     */
    public RankingDataSoap createRankingDataSoap() {
        return new RankingDataSoap();
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link Object }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://www.game_classes.com/soap-models", name = "RankingRequest")
    public JAXBElement<Object> createRankingRequest(Object value) {
        return new JAXBElement<Object>(_RankingRequest_QNAME, Object.class, null, value);
    }

}
