//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vhudson-jaxb-ri-2.1-2 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2023.07.07 at 06:43:39 PM EEST 
//

@javax.xml.bind.annotation.XmlSchema(namespace = "http://www.game_classes.com/soap-models", elementFormDefault = javax.xml.bind.annotation.XmlNsForm.QUALIFIED)
package com.game_classes.soap_models;
