//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vhudson-jaxb-ri-2.1-2 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2023.07.10 at 10:08:04 пр.об. EEST 
//


package com.game_classes.soap_models;

import java.util.ArrayList;
import java.util.List;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for anonymous complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType>
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="RankingDataSoap" type="{http://www.game_classes.com/soap-models}RankingDataSoap" maxOccurs="unbounded" minOccurs="0"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = {
    "rankingDataSoap"
})
@XmlRootElement(name = "RankingDataSoapList")
public class RankingDataSoapList {

    @XmlElement(name = "RankingDataSoap")
    protected List<RankingDataSoap> rankingDataSoap;

    /**
     * Gets the value of the rankingDataSoap property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the rankingDataSoap property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getRankingDataSoap().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link RankingDataSoap }
     * 
     * 
     */
    public List<RankingDataSoap> getRankingDataSoap() {
        if (rankingDataSoap == null) {
            rankingDataSoap = new ArrayList<RankingDataSoap>();
        }
        return this.rankingDataSoap;
    }

}
